import { Reservation } from "./reservation";

export interface User {
    id: number;  // Identity generated by the DB
    username: string;  // Valor predeterminado seguro para una propiedad requerida
    email: string;
    image: number;
    admin: boolean;  // Valor predeterminado
    enable: boolean;  // Valor predeterminado
    reservations?: Reservation[];  // Opcional, puede ser undefined si no hay reservaciones
}